name: Extract Article

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL of the article to extract'
        required: true
        default: 'https://example.com'

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and start Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx

      - name: Configure Nginx as a Proxy
        run: |
          echo 'server {
              listen 8080;
              location / {
                  proxy_pass https://api.ipify.org;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }' | sudo tee /etc/nginx/sites-available/default
          sudo systemctl restart nginx

      - name: Verify Proxy
        run: |
          response=$(curl -s -x http://localhost:8080 https://example.com)
          echo "Response from example.com: $response"
          echo "$response" > example_response.txt

      - name: Install dependencies
        run: |
          npm install @extractus/article-extractor

      - name: Run article extraction
        id: extract_article
        run: |
          echo "const input = '${{ github.event.inputs.url }}';" > extract.js
          echo "import('@extractus/article-extractor').then(({ extract }) => {" >> extract.js
          echo "  async function run() {" >> extract.js
          echo "    try {" >> extract.js
          echo "      const article = await extract(input, { headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0' }, proxy: 'http://localhost:8080' });" >> extract.js
          echo "      console.log(JSON.stringify(article, null, 2));" >> extract.js
          echo "      require('fs').writeFileSync('extracted-article.json', JSON.stringify(article, null, 2));" >> extract.js
          echo "    } catch (err) {" >> extract.js
          echo "      console.error(err);" >> extract.js
          echo "    }" >> extract.js
          echo "  }" >> extract.js
          echo "  run();" >> extract.js
          echo "});" >> extract.js
          node extract.js

      - name: Upload extracted article
        uses: actions/upload-artifact@v3
        with:
          name: extracted-article
          path: extracted-article.json

      - name: Send API request to ipify
        run: |
          response=$(curl -s -x http://localhost:8080 https://api.ipify.org)
          echo "Response from ipify: $response"
          echo "$response" > ipify_response.txt

      - name: Upload ipify response
        uses: actions/upload-artifact@v3
        with:
          name: ipify-response
          path: ipify_response.txt
